services:
  backend-api: 
    networks:
      - web
      - data
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    image: vasale01/backend:$${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"

  frontend: 
    networks:
      - web
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    image: "vasale01/frontend:$${IMAGE_TAG:-latest}"
    ports:
      - "8080:80"
    depends_on:
      - backend-api
    
  nginx: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    image: vasale01/nginx:$${IMAGE_TAG:-latest}
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend-api
    
  default-backend:
    networks:
      - web
    build: 
      context: .
      dockerfile: ./app/defaultbackend/Dockerfile
    image: vasale01/defaultbackend:$${IMAGE_TAG:-latest}
    ports:
      - "81:81"

networks:
  web:
  data: