services:
  backend-api: 
    networks:
      - web
      - data
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    image: backend-svc/backend-api:latest
    ports:
      - "8000:8000"

  frontend: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./app/frontend/Dockerfile
    image: frontend-svc/frontend-image:latest
    ports:
      - "8080:80"
    depends_on:
      - backend-api
    
  nginx: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx-svc/nginx:latest
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend-api


networks:
  web:
  data: