services:
  backend-api: 
    networks:
      - web
      - data
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    image: ferro21/backend:latest
    ports:
      - "8000:8000"

  frontend: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./app/frontend/Dockerfile
    image: ferro21/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend-api
    
  nginx: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    image: ferro21/nginx:latest
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend-api
    
  default-backend:
    networks:
      - web
    build: 
      context: .
      dockerfile: ./app/defaultbackend/Dockerfile
    image: vasale01/defaultbackend:latest
    ports:
      - "81:81"

networks:
  web:
  data: