services:
  backend-api: 
    networks:
      - web
      - data
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    image: vasale01/backend-api:latest
    ports:
      - "8000:8000"

  frontend: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./app/frontend/Dockerfile
    image: vasale01/frontend-image:latest
    ports:
      - "8080:80"
    depends_on:
      - backend-api
    environment:
      - VUE_APP_API_URL=/api
    
  nginx: 
    networks:
      - web
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    image: vasale01/nginx:latest
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend-api


networks:
  web:
  data: