name: rap-pop-env-training
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy
  - pip
  - scikit-learn
  - pandas
  - pip:
    - tensorflow==2.16.*
    - keras==2.16.*
    - inference-schema[numpy-support]==1.3.0
    - xlrd==2.0.1
    - mlflow==1.26.1
    - azureml-mlflow==1.42.0
    - Pillow==10.0.1