apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: genre-classifier-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: backend-svc/backend-api:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: genre-classifier-ns
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
