apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genre-classifier-ingress
  namespace: genre-classifier-ns
  annotations:
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend-api
            port:
              number: 8000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-api
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
