name: Deploy on Kubernetes
permissions:
  id-token: write
  contents: read

on:
  #workflow_run:
    #workflows: ["Retrain Model"]
    #types:
    #  - completed
  push:
    branches: [ "main" ]
    paths:
      - 'pipelines/**'
      - 'components/**'
      - 'environment/**'
      - '.github/workflows/deploy.yaml'
      - 'data/**'
jobs:
  redeploy:
    runs-on: self-hosted
    # needs: download
    # env: 
    #   IMAGE_TAG: ${{ github.sha }}
    # steps:
    #   - name: Check out repository
    #     uses: actions/checkout@v4
        
    #   - name: Docker login
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Build and push Docker image
    #     run: |
    #       docker build -t vasale01/backend:latest -f ./app/backend/Dockerfile .
    #       docker push vasale01/backend:latest
    steps:   
      - name: set up kubectl
        uses: azure/k8s-set-context@v1
        with: 
          kubeconfig: ${{ secrets.KUBECONFIG }}
  
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment backend-api
