name: CI/CD for Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker compose build
      run: |
        docker-compose build

    - name: docker compose push
      run: |
        docker-compose push

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/frontend-deployment frontend=${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.IMAGE_TAG }} -n default
        kubectl set image deployment/backend-deployment backend=${{ secrets.DOCKER_USERNAME }}/backend:${{ env.IMAGE_TAG }} -n default