name: Runtime deploy to k3d

# ────────────────────
# 1. Trigger
# ────────────────────
#   • Fires on every merge/push to main
#   • But only if frontend, backend, k8s manifests or env-files changed
on:
  push:
    branches: [main]
    paths:
      - "app/frontend/**"
      - "app/backend/**"
      - "app/defaultbackend/**"
      - "k8s/**"
      - "nginx/**"
      - "compose.yaml"
      - ".github/workflows/redeploy_app.yaml"

# ────────────────────

jobs:
  redeploy:
    runs-on: self-hosted          # your local runner that sees k3d
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:

    # 2. Checkout code that triggered the run
    - uses: actions/checkout@v4

    # 3. (Optional) Build & push backend image if backend code changed
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: run npm install & build for frontend
      run: |
        cd app/frontend/genre-classifier
        npm install
        npm run build

    - name: docker compose build & push
      run: |
        docker compose build
        docker compose push
      
      
    - name: set up kubectl
      uses: azure/k8s-set-context@v1
      with: 
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Apply updated Kubernetes manifests
     # if: github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), 'k8s/')
      run: |
        kubectl apply -f k8s/

    - name: Roll backend deployment if new image
    #  if: ${{ github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), 'app/backend/') }}
      run: |
        kubectl set image deployment/backend-api \
          backend-api=vasale01/backend:${IMAGE_TAG}
        kubectl rollout status deployment/backend-api

    - name: Roll frontend deployment if new image
    #  if: ${{ github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), 'app/frontend/') }}
      run: |
        kubectl set image deployment/frontend \
          frontend=vasale01/frontend:${IMAGE_TAG}
        kubectl rollout status deployment/frontend
      
    - name: Roll default backend deployment if new image
     # if: ${{ github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), 'app/defaultbackend/') }}
      run: |
        kubectl set image deployment/default-backend \
          default-backend=vasale01/defaultbackend:${IMAGE_TAG}
        kubectl rollout status deployment/default-backend

    - name: Roll nginx deployment if new image
    #  if: ${{ github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), 'nginx/') }}
      run: |
        kubectl set image deployment/nginx \
          nginx=vasale01/nginx:${IMAGE_TAG}
        kubectl rollout status deployment/nginx

    - name: Restart pods after manifest-only changes
     # if: github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), 'k8s/')
      run: |
        kubectl rollout restart deployment/backend-api
        kubectl rollout restart deployment/frontend
        kubectl rollout restart deployment/frontend
