# This is a basic workflow to help you get started with Actions

name: Retrain Model
permissions:
  id-token: write
  contents: read


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'pipelines/**'
      - 'components/**'
      - 'environment/**'
      - '.github/workflows/retrain.yml'
      - 'data/**'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Compute Start
        uses: azure/cli@v2.1.0
        with:
          azcliversion: 'latest'
          inlineScript: |
            
            az extension add -n ml -y
            az configure --defaults group=${{secrets.RG}} workspace=${{secrets.WG}} location=$LOCATION
            az ml compute create -f ./environment/compute.yaml 
            
            # Start only if the compute instance is currently Stopped
           
            STATE=$(az ml compute show --name cli-machine --query state -o tsv || echo "Unknown")
            if [ "$STATE" = "Stopped" ]; then
              az ml compute start --name cli-machine
            else
              echo "Compute instance is already $STATE — skipping start."
            fi
    

      - name: Azure - environment setup
        uses: azure/cli@v2.1.0
        with: 
          azcliversion: 'latest'
          inlineScript: |
            az extension add -n ml -y
            az configure --defaults group=${{secrets.RG}} workspace=${{secrets.WG}} location=$LOCATION

            az ml environment create -f ./environment/tensorflow.yaml
        continue-on-error: true

      - name: Azure - component setup
        uses: azure/cli@v2.1.0
        with:
          azcliversion: 'latest'
          inlineScript: |
            az extension add -n ml -y
            az configure --defaults group=${{secrets.RG}} workspace=${{secrets.WG}} location=$LOCATION

            az ml component create -f ./components/code/datasplit.yaml
            az ml component create -f ./components/code/preprocess.yaml
            az ml component create -f ./components/code/training.yaml
            
 
      - name: Run Pipeline
        uses : azure/cli@v2.1.0
        with:  
          azcliversion: 'latest'
          inlineScript: |
            az extension add -n ml -y
            az configure --defaults group=${{secrets.RG}} workspace=${{secrets.WG}} location=$LOCATION

            az ml job create \
              --file ./pipelines/pipeline.yaml \
              -g ${{ secrets.RG }} \
              -w ${{secrets.WG}} \
              --set compute=cli-machine \
              --set experiment_name=rap-vs-pop-retrain \
              --set name = rap-vs-pop-classifier-${{github.sha}}-${{github.run_id}} \
              --stream

      - name: Compute Stop
        uses: azure/cli@v2.1.0
        with:
          azcliversion: 'latest'
          inlineScript: |
            az extension add -n ml -y
            az configure --defaults group=${{secrets.RG}} workspace=${{secrets.WG}} location=$LOCATION
            az ml compute stop --name cli-machine
        continue-on-error: true
            
        
        
  



      


