# This is a basic workflow to help you get started with Actions

name: Retrain Model
permissions:
  id-token: write
  contents: read


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Ensure compute & submit pipeline via Azure CLI action
        uses: azure/cli@v1
        with:
          azcliversion: 'latest'
          inlineScript: |
            az config set extension.dynamic_install_allow_preview=true
            
            az extension add -n ml -y

            az ml compute show -n cpu-cluster -g ${{ secrets.RG }} -w project-alex \
              || az ml compute create -n cpu-compute \
                  -g ${{ secrets.RG }} \
                  -w project-alex \
                  --type compute-instance \
                  --min-instances 0 \
                  --max-instances 4 \
                  --idle-time-before-scale-down 30

            az ml job create \
              --file ./pipelines/pipeline.yaml \
              -g ${{ secrets.RG }} \
              -w project-alex \
              --set compute=cpu-cluster \
              --set experiment_name=rap-vs-pop-retrain
        
  



      


